spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://localhost:3306/tacomall?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
  redis:
    host: 172.23.121.176
    port: 3000
    password: 12345678
    timeout: 3000
    database: 0
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100
        min-idle: 4
logback:
  path: ../../.log/api-admin/