server:
  port: 4000

spring:
  profiles:
    active: @environment@
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.baomidou: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: store.tacomall.common.mapper
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
swagger:
  flag: true
  host: localhost
