spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: 
          password: 
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
logback:
  path: /var/log/tacomall-api/api-shop/